[package]
name = "odoh-rs"
version = "1.0.0-alpha.1"
authors = ["Tanya Verma <tverma@cloudflare.com>"]
edition = "2021"
license = "BSD-2-Clause"
description = "Rust implementation of the Oblivious DNS over HTTPS (ODoH) protocol version 1"
repository = "https://github.com/cloudflare/odoh-rs/"
keywords = ["odoh", "protocols", "dns", "doh", "privacy"]
categories = ["network-programming", "cryptography"]

[dependencies]
aes-gcm = { version = "0.9.4", features = [ "std" ] }
bytes = "1.1.0"
hkdf = "0.12.3"
hpke = { git = "https://github.com/junkurihara/rust-hpke.git", features = [ "std", "x25519" ], default-features = false }
rand = { version = "0.8.5", features = [ "std_rng" ], default-features = false }
thiserror = "1.0.30"

[dev-dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.10", features = ["derive"] }
criterion = "0.3.5"
domain = "0.6.1"
env_logger = "0.9.0"
hex = "0.4.3"
log = "0.4.16"
rand = "0.8.5"
reqwest = "0.11.10"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = [ "full" ] }

[[bench]]
name = "odoh_bench"
harness = false
