[package]
name = "odoh-rs"
version = "1.0.0"
authors = ["Tanya Verma <tverma@cloudflare.com>"]
edition = "2021"
license = "BSD-2-Clause"
description = "Rust implementation of the Oblivious DNS over HTTPS (ODoH) protocol version 1"
repository = "https://github.com/cloudflare/odoh-rs/"
keywords = ["odoh", "protocols", "dns", "doh", "privacy"]
categories = ["network-programming", "cryptography"]
include = ["/src", "/examples", "README.md", "LICENSE"]

[dependencies]
aes-gcm = { version = "0.10.1", features = [ "std" ] }
bytes = "1.2.1"
hkdf = "0.12.3"
hpke = { git = "https://github.com/junkurihara/rust-hpke.git", features = [ "std", "x25519" ], default-features = false }
rand = { version = "0.8.5", features = [ "std_rng" ], default-features = false }
thiserror = "1.0.35"

[dev-dependencies]
anyhow = "1.0.65"
clap = { version = "3.2.22", features = ["derive"] }
criterion = "0.4.0"
domain = "0.7.0"
env_logger = "0.9.1"
hex = "0.4.3"
log = "0.4.17"
rand = "0.8.5"
reqwest = "0.11.12"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1.21.1", features = [ "full" ] }

[[bench]]
name = "odoh_bench"
path = "benches/odoh_bench.rs"
harness = false
